 
 ​name​: ​'​Labeler​' 
 ​description​: ​'​Automatically label new pull requests based on the paths of files being changed​' 
 ​author​: ​'​monstro805​' 
 ​inputs​: 
 ​  ​repo-token​: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 
 ​    ​description​: ​'​The GITHUB_TOKEN secret​' 
 ​  ​configuration-path​: 
 ​    ​description​: ​'​The path for the label configurations​' 
 ​    ​default​: ​'​.github/labeler.yml​' 
 ​    ​required​: true
 ​  ​sync-labels​: 
 ​    ​description​: ​'​Whether or not to remove labels when matching files are reverted​' 
 ​    ​default​: ​false 
 ​    ​required​: ​false 
  
 ​runs​: 
 ​  ​using​: ​'​node@2​' 
 ​  ​main​: ​'​m1cal.workflows/.yaml'
