version: '2.1' orbs: renovate: daniel-shuy/renovate@2.1.1 workflows: renovate: jobs: - renovate/self-hosted: config_file_path: renovate-config.js nightly: triggers: - schedule: cron: 0 * * * * filters: branches: only: - main
